application: myembeddedlife
version: 3
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /(favicon.ico)
  static_files: \1
  upload: favicon.png
- url: /(robots.txt)
  static_files: \1
  upload: robots.txt
- url: /(sitemap.xml)
  static_files: \1
  upload: sitemap.xml
- url: /(google5228ccde1df7ede3.html)
  static_files: \1
  upload: google5228ccde1df7ede3.html
- url: /(.*\.(gif|png|jpg|ico|js|css|xml))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css|xml))
- url: /.*
  script: main.app
